apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-metrics-app-sm  
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: node-metrics-app  
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http 
      path: /metrics
      interval: 10s
